### ISSUE TITLE
Doesn't work anymore with VS Code 1.0

### ISSUE THREAD

**Issue by jp7677** [chenxsan/vscode-standardjs#2]
Hello there,

I love your extension since it just worked without any special setup steps. Unfortunately I don't get javascripts hints anymore with VS Code 1.0 (or at least I think that standardjs stopped working with release 1.0). Could you please take a look at this? I have my solution in github, if it helps please look at [https://github.com/jp7677/hellocoreclr](https://github.com/jp7677/hellocoreclr). I used to have standard hints when editing all my js files, but not anymore. Thanks in advance!

**Comment by chenxsan** [comment]
Hi, it's because there is no `package.json` file under your project root, just add one with an empty object:

```
{}
```
Since global `standard` works without a `package.json`, So I think it's a bug in the extension. I'll push a fix when I have some time.

**Comment by chenxsan** [comment]
Fixed in https://github.com/chenxsan/vscode-standardjs/commit/a4dd61003c5f536632ca7960ec3024c93b786cb3.

**Comment by jp7677** [comment]
Indeed, confirmed on my setup. Thanks a lot!
