### ISSUE TITLE
Support for standard and ts-standard in mixed projects

### ISSUE THREAD

**Issue by sarensw** [chenxsan/vscode-standardjs#285]
**What version of this package are you using?**
2.0.0

**What problem do you want to solve?**
I have build an Electron app with js and I've been using standard without any issue so far. Now I want to move to ts, step by step. But I can only choose either standard or ts-standard. I want to be able to use standard for .js / .jsx files and ts-standard for .ts and .tsx files.  

**What do you think is the correct solution to this problem?**
Let the user choose an engine for .js/.jsx files and one engine for .ts/.tsx files. Or decide this based on the file extension by default.

**Are you willing to submit a pull request to implement this change?**
I checked the code for 20mins already, but I have some troubles for now to understand where exactly the linter is called. But I guess this is due to a lack on developing VS code extensions. Any hint would be helpful

(Created the ticket as per suggestion by @voxpelli in the discord channel)

**Comment by voxpelli** [comment]
I agree that the extension ideally should be able to lint both js and ts at once, but I leave to others whether its already possible or what it would take. Thanks for filing the issue @sarensw 🙏

**Comment by theoludwig** [comment]
`ts-standard` allows to lint `.js`, `.jsx`, `.ts` and `.tsx` files whereas `standard` only lint `.js` and `.jsx` files.

In short, if you have at least one `.ts` file in your project, you should not install `standard` (or uninstall it if you installed it before, `npm uninstall standard`) and you should install/use `ts-standard`.

So yes it is already possible to lint both JavaScript and TypeScript files at once.

Does that solve your issue? @sarensw

**Comment by sarensw** [comment]
@Divlo thanks for this info. I wanted to verify this now, but when I enable ts-standard, still nothing happens. I also restarted VS Code a couple of times but nothing is highlighted. The logs say:

```
[Info  - 5:10:43 AM] TypeScript Standard Style server stopped.
[Info  - 5:10:44 AM] TypeScript Standard Style server is running.
[Info  - 5:10:44 AM] TypeScript Standard Style library loaded from: /Users/sarensw/Documents/work-a/braindump/node_modules/ts-standard/dist/index.js
[Info  - 5:10:45 AM] Failed to load the TypeScript Standard Style library for the document /Users/sarensw/Library/Application Support/Code/User/settings.json
To use TypeScript Standard Style for single JavaScript file install standard globally using 'npm install -g ts-standard'.
You need to reopen VS Code after installing ts-standard.
[Info  - 5:10:45 AM] Failed to load the TypeScript Standard Style library for the document /Users/sarensw/Library/Application Support/Code/User/keybindings.json
To use TypeScript Standard Style for single JavaScript file install standard globally using 'npm install -g ts-standard'.
You need to reopen VS Code after installing ts-standard. 
```

I have uninstalled standard from the repo before installing ts-standard. I have also set ts-standard as the default in the settings.json (using the VS code UI).

Is there anything obvious missing?

(Btw: I have also tried to install ts-standard globally, but I miss admin rights on my laptop, so I can't do that)

**Comment by theoludwig** [comment]
I can't reproduce the issue. @sarensw 
Here's a minimal example with both JavaScript and TypeScript files using `ts-standard` for linting:
![test-ts-js-vscode-standard](https://user-images.githubusercontent.com/25207499/134222084-8791bd04-f72d-4507-a5e5-16a553a75f96.png)

There are no settings needed for this extension by default, it is enabled if you open the folder (only one) in VSCode, and `ts-standard` is installed.
As you can see I get the accurate linting error, for both JavaScript and TypeScript files (in this example, the extra semicolon).

If the issue persists, could you tell us how to reproduce it?

**Comment by sarensw** [comment]
Oh, I don't have a tsconfig.json yet O.O. I assume this could be the problem, right @Divlo ? (I will give it a try)

**Comment by theoludwig** [comment]
Yes, you need a `tsconfig.json` file to work with `ts-standard`.

**Comment by sarensw** [comment]
I can indeed confirm that this was the issue. Thanks @Divlo for your your help.
