### ISSUE TITLE
standard stops to lint inside a Multi-root workspace

### ISSUE THREAD

**Issue by bjrmatos** [chenxsan/vscode-standardjs#305]
**What version of this package are you using?**
2.0.0

**What operating system, Node.js, and npm version?**
macOS High Sierra (10.13.6), Node.js 16.8.0, npm 7.21.0

**What happened?**
I started a new window of vscode, added a project folder with standard installed and just one file (`index.js`), i can see the linting is working as expected.

<img width="1027" alt="Captura de pantalla 2021-10-15 a la(s) 3 32 45 p  m" src="https://user-images.githubusercontent.com/4262050/137550245-0df7ae73-3e38-4b81-a9b9-b5e41c16911a.png">

However, if I add a new folder (even an empty one) to the vscode window, with `File -> Add Folder to Workspace` the lint appears to continue to work until I restart the vscode, after that the lint no longer activates again.

<img width="2048" alt="Captura de pantalla 2021-10-15 a la(s) 3 41 36 p  m" src="https://user-images.githubusercontent.com/4262050/137551200-7e0110db-e68f-446f-a9ad-b0e85518762f.png">

**What did you expect to happen?**

I expected the lint to the `index.js` to continue to work, by looking at the options I am not sure if I am missing to enable something else, I am just using the default options, perhaps the `standard.workingDirectories` is needed here? I am not sure what the option is for, tried to use it but it seems it is not relevant to this problem.

**Are you willing to submit a pull request to fix this bug?**
No, though if someone guides me to where to look in the code, I will happily check if I can fix it

**Comment by theoludwig** [comment]
Hey, @bjrmatos! :wave:

Thanks for your report! :smile: 

That's the expected behavior, read [v2.0.0](https://github.com/standard/vscode-standard/releases/tag/v2.0.0) changelog for details, as you might use `standard` in one folder, in another `ts-standard` and in a third open folder in the workspace `eslint`.

It might be complicated to auto-detect automatically what engines to use and load them at the same time.

The way to do this currently is to open your 2 folders as you showed on your screen, as it is one folder.
Inside VSCode: File -> Open Folder, and then select your folder containing the 2 subfolders you wanna lint.

> I am just using the default options, perhaps the `standard.workingDirectories` is needed here?

Yes, exactly it is needed in this situation.

Add a `.vscode/settings.json` file in the root folder you opened with:
```jsonc
{
  "standard.enable": true,
  "standard.enableGlobally": true, /* you would need to install `standard` globally in this case, if you didn't installed it in the root folder, `npm install --global standard` for example. */
  "standard.engine": "standard", /* this could be `standard`, or `standardx` or `semistandard` or `ts-standard` */
  "standard.workingDirectories": ["first-folder", "second-folder"]
}
```

**Comment by bjrmatos** [comment]
@Divlo thanks for the details

so if I understand this correctly in a multi-root workspace the extension need to be enabled more manually with settings (either in workspace settings or in folder settings) because it is not able to auto-detect.

I realized that my issue is solved if I create a `vscode/settings.json` in `test-vscode-standard` folder with 

```json
{
  "standard.enableGlobally": true
}
```

with that option, it seems vscode-standard is able to use my package.json again and detect the version of the standard i have installed. the lint works again.


> The way to do this currently is to open your 2 folders as you showed on your screen, as it is one folder.
> Inside VSCode: File -> Open Folder, and then select your folder containing the 2 subfolders you wanna lint.

so the workaround here to have the auto-detect working will be to open just one folder in vscode, and it should be folder that contains the 2 projects, right? it is a bit hard for me to do this because the common folder for the 2 projects I show in the screenshot is a folder that contains all my local projects, I understand that I can workaround this by changing how I organize the projects, but this is a big change, and one of the reasons I was excited to discover that vscode supported this multi-root concept.



> Yes, exactly it is needed in this situation.
> 
> Add a `.vscode/settings.json` file in the root folder you opened with:

just to know if I understand this clearly, these steps are needed if I decide to open one root folder that contains my 2 projects, right? I think I understand now that in this case `standard.workingDirectories` is needed to tell vscode-standard to run as is `first-folder` and `second-folder` are the root in each case. is this correct?

**Comment by theoludwig** [comment]
> so the workaround here to have the auto-detect working will be to open just one folder in vscode, and it should be folder that contains the 2 projects, right?

> just to know if I understand this clearly, these steps are needed if I decide to open one root folder that contains my 2 projects, right? I think I understand now that in this case standard.workingDirectories is needed to tell vscode-standard to run as is first-folder and second-folder are the root in each case. is this correct?

Yes, it is right! @bjrmatos 

Please close this issue, if your problem is solved. :smile:

**Comment by bjrmatos** [comment]
Thanks again for the details @Divlo 

All clear now!

**Comment by natcl** [comment]
Is there a way to make this work with the add folder to workspace ?
In my case I cannot put all my folder under the same folder..
Thanks !

**Comment by bjrmatos** [comment]
>I realized that my issue is solved if I create a vscode/settings.json in test-vscode-standard folder with

```js
{
  "standard.enableGlobally": true
}
```
>with that option, it seems vscode-standard is able to use my package.json again and detect the version of the standard i have installed. the lint works again.

@natcl try this

**Comment by natcl** [comment]
I was able to make it work by adding 
```
{
  "standard.enableGlobally": true
}
```
To the settings section of my workspace file. Seems to work for every folder now.
Thanks !
