### ISSUE TITLE
Extension not running

### ISSUE THREAD

**Issue by paulpe-rr** [chenxsan/vscode-standardjs#315]
**What version of this package are you using?** 2.0.1 ( also tried on 2.0.0 )

**What operating system, Node.js, and npm version?**
Windows 10 x64
npm 7.5.2
node v14.15.1
vscode v1.61.2

**What happened?**
Extension doesn't run / appear in Output tab of VsCode.

- Works right in version 1.5.1 of Extension, using this as workaround for now
- I checked that all my projects I want to be linted have "ts-standard" listed under devDependencies in their respective package.json
- ts-standard is obviously working in console/outside the extension

Here are my full workspace settings ( nothing overriden higher up )
```json
{
  "folders": [
    {
        "path": "ooda"
    },
    {
        "path": "ooda\\Clients\\Admin"
    },
    {
        "path": "ooda\\Clients\\Agenz"
    },
    {
        "path": "ooda\\Constellation\\Flow\\Flow.Engine"
    }
  ],
  "settings": {
    "javascript.validate.enable": false,
    "typescript.validate.enable": false,
    "standard.enable": true,
    "standard.engine": "ts-standard",
    "standard.usePackageJson": true
  }
}
```

**What did you expect to happen?**
Extension runs / lints properly.

**Are you willing to submit a pull request to fix this bug?**
Don't think I have enough time to investigate in a new project right now, sorry :/

**Comment by paulpe-rr** [comment]
Resolved, don't find the Changelog entry that clear tho, at least in my use-case ?

Had to add `standard.enableGlobally: true` to make it work with 2.0.0^

From Changelog:

> 2.0.0
...
BREAKING CHANGE: By default (if you don't set "standard.enableGlobally": true), the extension will not lint your files if you haven't got a package.json containing one of the engines installed in devDependencies.

Should probably state it doesn't work either with package.json other than in the project's root, unlike before ?
As I had ts-standard listed under all of my package.json ( but not at project's root ) I expected it to work.

**Comment by theoludwig** [comment]
Hey! :wave: @paperrin 

Sorry for the late reply and thank you for your report, glad that you find yourself how to solve the issue.

> Should probably state it doesn't work either with package.json other than in the project's root, unlike before ?
As I had ts-standard listed under all of my package.json ( but not at project's root ) I expected it to work.

Yes, that's the expected behavior, but maybe that wasn't clear enough in the changelog, or in the documentation `README`, feel free to open a PR to improve that, for the moment I'll close this issue. :smile:
