### ISSUE TITLE
Add support for Standard 17

### ISSUE THREAD

**Issue by NemoStein** [chenxsan/vscode-standardjs#375]
**What version of this package are you using?**
2.0.1

**What problem do you want to solve?**
Standard 17 changed some internals, breaking compatibility

**What do you think is the correct solution to this problem?**

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by theoludwig** [comment]
Indeed `standard-engine` changed a lot between v14 and v15.
The idea is that we support both `standard-engine` versions to begin with to avoid **BREAKING CHANGE**.
We will drop support for `standard-engine@14` when we release v3.0.0 of `vscode-standard`, probably next year or even later.

Thanks for your PR, I'll check that out and also test it manually. :+1:
