### ISSUE TITLE
Code improvement (no usage of `eval`) to import ESM and require modules

### ISSUE THREAD

**Issue by theoludwig** [chenxsan/vscode-standardjs#378]
Problematic lines:

https://github.com/standard/vscode-standard/blob/b70aca78afc36b0e8101e0265614af71cb8265dc/server/src/server.ts#L428-L429

Ref: https://github.com/standard/vscode-standard/pull/376#discussion_r799071006

Once TypeScript doesn't transpile `await import` to `require`  we'll be able to change that to be simpler and safer.

**Comment by LinusU** [comment]
Could also be solved by: https://github.com/microsoft/vscode/issues/130367

**Comment by theoludwig** [comment]
Unlikely to be done.
