### ISSUE TITLE
detect language based on extension

### ISSUE THREAD

**Issue by pe1pip** [chenxsan/vscode-standardjs#382]
**What version of this package are you using?**
2.1.0
**What problem do you want to solve?**

We are developing both javascript and typescript, it would be nice to have the engine be determined based on the file type (.js vs .ts)

**What do you think is the correct solution to this problem?**

**Are you willing to submit a pull request to implement this change?**

**Comment by theoludwig** [comment]
Hey! :wave: @pe1pip

Thanks for your report!
We already have auto-detection of the engine (`standard`, `semistandard`, `standardx` or `ts-standard`) you are using.
If you work with both JavaScript and TypeScript files, you should use `ts-standard`, so you can simply run this in your project and it should work: `npm install --save-dev ts-standard`.

Please, close this issue if it resolved your problem. :smile:

**Comment by pe1pip** [comment]
You are right. Unfortunately we are stuck on an ancient javascript engine (vRealize orchestrator) that doesn't understand let, so we're stuck a standard 15. I guess this is a corner case that you may choose not to support. Thanks for your reply.
