### ISSUE TITLE
standard.engine => This setting does not support per-language configuration.

### ISSUE THREAD

**Issue by LuisEnMarroquin** [chenxsan/vscode-standardjs#384]
**What version of this package are you using?**

Version: `v2.1.0`

![image](https://user-images.githubusercontent.com/35376824/155039758-93c81985-777f-4e40-bb8c-5172fffdfd16.png)

**What problem do you want to solve?**

This setting is only supported as a top level setting: `"standard.engine": "ts-standard"`

![image](https://user-images.githubusercontent.com/35376824/155039876-1c0e2283-440b-466b-8978-b0a7ff5e3e9e.png)

**What do you think is the correct solution to this problem?**

Will be good to support this setting per language so I can globally set `standard` for `js` and `ts-standard` for `ts`

```json
  "[javascript]": {
    "standard.engine": "standard",
    "editor.defaultFormatter": "standard.vscode-standard"
  },
  "[javascriptreact]": {
    "standard.engine": "standard",
    "editor.defaultFormatter": "standard.vscode-standard"
  },
  "[typescript]": {
    "standard.engine": "ts-standard",
    "editor.defaultFormatter": "standard.vscode-standard"
  },
  "[typescriptreact]": {
    "standard.engine": "ts-standard",
    "editor.defaultFormatter": "standard.vscode-standard"
  },
```

![image](https://user-images.githubusercontent.com/35376824/155039929-3429c476-30cd-474d-a938-e15ca4d53e8b.png)

**Are you willing to submit a pull request to implement this change?**

I don't have enough experience working on vs code extensions, I can help if you tell me what to do

**Comment by theoludwig** [comment]
Hey! :wave: @LuisEnMarroquin 
Thanks for your report!

If you are in a project using both JavaScript and TypeScript files, you should only use `ts-standard` and not `standard`.
So we don't need to specify the engine to use per language.
Please close the issue, if it solves your problem.
