### ISSUE TITLE
Use `standard-react` instead of `standard` if presented.

### ISSUE THREAD

**Issue by chenxsan** [chenxsan/vscode-standardjs#4]

**Comment by chenxsan** [comment]
close it with commit https://github.com/chenxsan/vscode-standardjs/commit/6d0a941f8916d9d553373b6c49c7e18a08aacbeb.

**Comment by ganevdev** [comment]
This still works only if "standard.run": "onType" and does not work when "onSave". Perhaps it's worth writing about this in the description?
