### ISSUE TITLE
Access Token used has expired to publish new versions on VSCode marketplace

### ISSUE THREAD

**Issue by theoludwig** [chenxsan/vscode-standardjs#444]
We can't release new versions as the access token has expired for the VSCode marketplace.

See: https://github.com/standard/vscode-standard/actions/runs/2747401022

**Comment by voxpelli** [comment]
Right, so we need to do:

1. Preferably [add more people](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token) to the VSCode Marketplace organization
2. Get a new VSCode marketplace [personal access token](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token) for someone

On top of that it would be good to also do these while we're at it:

1. [Verify our publisher](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher) through the standardjs.com domain
2. Lock down the [HaaLeo/publish-vscode-extension](https://github.com/HaaLeo/publish-vscode-extension) to a specific hash, like currently [`96a0a72`](https://github.com/HaaLeo/publish-vscode-extension/commit/96a0a72f3c7b691ae5e45183aaadceb0599df89e). This to avoid a potential compromise of that repo to cause additional spreading through our repository.

**Comment by feross** [comment]
1. Who is best to add? @LinusU @Divlo?
2. Just got a new personal access token (they only last for 1 year) and added it into this repo.
3. I just added the TXT record for verifying the publisher and submitted the request. Once the VSCode team approves, it should be live.

**Comment by theoludwig** [comment]
Thanks @feross!
We can probably add @voxpelli, @LinusU and me @Divlo.
My email address is `contact@divlo.fr`.

@voxpelli email address should be `pelle@kodfabrik.se`.

For v2.1.1 we can probably do a manual release, because the GitHub Actions already ran and published on `open-vsx`.
I'm up to do that, once I'm added to the `standard` organization on the VSCode marketplace. :+1:

**Comment by theoludwig** [comment]
Fixed by https://github.com/standard/vscode-standard/commit/7167ab8077f85764c945e9c48f2d2dd643895278.
The new release should be published both on Open VSX and the VSCode Marketplace.
