### ISSUE TITLE
Enabling standardFormat.formatOnSave keep on showing file as unsaved.

### ISSUE THREAD

**Issue by Ankitdave87** [chenxsan/vscode-standardjs#6]
After enabling standardFormat.formatOnSave file always stays unsaved. It format code correctly but after that it starts showing file as not saved and for saving file must be closed once.

**Comment by chenxsan** [comment]
Check https://github.com/chenxsan/vscode-standard-format/issues/6.

**Comment by Ankitdave87** [comment]
OK thanks
